import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Share the Pie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppProvider>
      <html lang='en'>
        <head>
          <link rel='manifest' href='/manifest.json' />
        </head>
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </AppProvider>
  );
}
